lrt1_fare_matrix = {
    "Baclaran":                 {
        "Baclaran":                 0,
        "EDSA":                     14,
        "Libertad":                 15,
        "Gil Puyat":                16,
        "Vito Cruz":                17,
        "Quirino":                  18,
        "Pedro Gil":                19,
        "United Nations":           20,
        "Central Terminal":         22,
        "Carriedo":                 23,
        "Doroteo Jose":             23,
        "Bambang":                  24,
        "Tayuman":                  25,
        "Blumentritt":              26,
        "Jose Abad Santos":         27,
        "R.Papa":                   28,
        "5th Avenue":               29,
        "Yamaha Monumento":         30,
        "Balintawak":               33,
        "Roosevelt":                35,
    },
    "EDSA":                     {
        "Baclaran":                 14,
        "EDSA":                     0,
        "Libertad":                 15,
        "Gil Puyat":                15,
        "Vito Cruz":                17,
        "Quirino":                  18,
        "Pedro Gil":                19,
        "United Nations":           20,
        "Central Terminal":         21,
        "Carriedo":                 22,
        "Doroteo Jose":             23,
        "Bambang":                  24,
        "Tayuman":                  24,
        "Blumentritt":              25,
        "Jose Abad Santos":         26,
        "R.Papa":                   27,
        "5th Avenue":               28,
        "Yamaha Monumento":         29,
        "Balintawak":               32,
        "Roosevelt":                34,
    },
    "Libertad":                 {
        "Baclaran":                 15,
        "EDSA":                     15,
        "Libertad":                 0,
        "Gil Puyat":                14,
        "Vito Cruz":                15,
        "Quirino":                  16,
        "Pedro Gil":                17,
        "United Nations":           18,
        "Central Terminal":         20,
        "Carriedo":                 21,
        "Doroteo Jose":             22,
        "Bambang":                  22,
        "Tayuman":                  23,
        "Blumentritt":              24,
        "Jose Abad Santos":         25,
        "R.Papa":                   26,
        "5th Avenue":               27,
        "Yamaha Monumento":         28,
        "Balintawak":               31,
        "Roosevelt":                33,
    },
    "Gil Puyat":                {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Vito Cruz":                {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Quirino":                  {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Pedro Gil":                {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "United Nations":           {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Central Terminal":         {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Carriedo":                 {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Doroteo Jose":             {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Bambang":                  {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Tayuman":                  {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Blumentritt":              {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Jose Abad Santos":         {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "R.Papa":                   {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "5th Avenue":               {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Yamaha Monumento":         {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Balintawak":               {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
    "Roosevelt":                {
        "Baclaran":                 21,
        "EDSA":                     22,
        "Libertad":                 23,
        "Gil Puyat":                24,
        "Vito Cruz":                25,
        "Quirino":                  26,
        "Pedro Gil":                27,
        "United Nations":           28,
        "Central Terminal":         29,
        "Carriedo":                 30,
        "Doroteo Jose":             31,
        "Bambang":                  32,
        "Tayuman":                  33,
        "Blumentritt":              34,
        "Jose Abad Santos":         35,
        "R.Papa":                   35,
        "5th Avenue":               37,
        "Yamaha Monumento":         38,
        "Balintawak":               41,
        "Roosevelt":                43,
    },
}

lrt2_fare_matrix = {
    "Recto": {"Recto": 13, "Legarda": 15, "Pureza": 16, "V. Mapa": 18, "J. Ruiz": 19,
              "Gilmore": 21, "Betty Go": 22, "Cubao2": 23, "Anonas": 25, "Katipunan": 26,
              "Santolan": 28, "Marikina": 31, "Antipolo": 33},
    
    "Legarda": {"Recto": 15, "Legarda": 13, "Pureza": 15, "V. Mapa": 17, "J. Ruiz": 18,
                "Gilmore": 19, "Betty Go": 21, "Cubao2": 22, "Anonas": 24, "Katipunan": 25,
                "Santolan": 27, "Marikina": 29, "Antipolo": 32},
    
    "Pureza": {"Recto": 16, "Legarda": 15, "Pureza": 13, "V. Mapa": 15, "J. Ruiz": 16,
               "Gilmore": 18, "Betty Go": 19, "Cubao2": 20, "Anonas": 22, "Katipunan": 23,
               "Santolan": 26, "Marikina": 28, "Antipolo": 30},
    
    "V. Mapa": {"Recto": 18, "Legarda": 17, "Pureza": 15, "V. Mapa": 13, "J. Ruiz": 15,
                "Gilmore": 17, "Betty Go": 19, "Cubao2": 20, "Anonas": 22, "Katipunan": 24,
                "Santolan": 26, "Marikina": 29, "Antipolo": 30},
    
    "J. Ruiz": {"Recto": 19, "Legarda": 18, "Pureza": 16, "V. Mapa": 15, "J. Ruiz": 13,
                "Gilmore": 16, "Betty Go": 17, "Cubao2": 19, "Anonas": 20, "Katipunan": 22,
                "Santolan": 24, "Marikina": 27, "Antipolo": 29},
    
    "Gilmore": {"Recto": 21, "Legarda": 19, "Pureza": 18, "V. Mapa": 16, "J. Ruiz": 14,
                "Gilmore": 13, "Betty Go": 15, "Cubao2": 16, "Anonas": 18, "Katipunan": 19,
                "Santolan": 21, "Marikina": 23, "Antipolo": 26},
    
    "Betty Go": {"Recto": 22, "Legarda": 21, "Pureza": 19, "V. Mapa": 17, "J. Ruiz": 16,
                 "Gilmore": 13, "Betty Go": 13, "Cubao2": 15, "Anonas": 16, "Katipunan": 18,
                 "Santolan": 20, "Marikina": 22, "Antipolo": 25},
    
    "Cubao2": {"Recto": 23, "Legarda": 22, "Pureza": 20, "V. Mapa": 17, "J. Ruiz": 16,
              "Gilmore": 15, "Betty Go": 13, "Cubao2": 13, "Anonas": 15, "Katipunan": 16,
              "Santolan": 19, "Marikina": 21, "Antipolo": 23},
    
    "Anonas": {"Recto": 25, "Legarda": 24, "Pureza": 22, "V. Mapa": 19, "J. Ruiz": 18,
               "Gilmore": 16, "Betty Go": 15, "Cubao2": 13, "Anonas": 13, "Katipunan": 14,
               "Santolan": 17, "Marikina": 19, "Antipolo": 22},
    
    "Katipunan": {"Recto": 26, "Legarda": 25, "Pureza": 23, "V. Mapa": 20, "J. Ruiz": 19,
                  "Gilmore": 18, "Betty Go": 16, "Cubao2": 15, "Anonas": 13, "Katipunan": 13,
                  "Santolan": 16, "Marikina": 18, "Antipolo": 21},
    
    "Santolan": {"Recto": 28, "Legarda": 27, "Pureza": 26, "V. Mapa": 22, "J. Ruiz": 21,
                 "Gilmore": 19, "Betty Go": 18, "Cubao2": 16, "Anonas": 14, "Katipunan": 13,
                 "Santolan": 13, "Marikina": 15, "Antipolo": 18},
    
    "Marikina": {"Recto": 31, "Legarda": 29, "Pureza": 28, "V. Mapa": 26, "J. Ruiz": 24,
                 "Gilmore": 23, "Betty Go": 22, "Cubao2": 21, "Anonas": 19, "Katipunan": 18,
                 "Santolan": 15, "Marikina": 13, "Antipolo": 16},
    
    "Antipolo": {"Recto": 33, "Legarda": 32, "Pureza": 30, "V. Mapa": 29, "J. Ruiz": 27,
                 "Gilmore": 26, "Betty Go": 25, "Cubao2": 23, "Anonas": 22, "Katipunan": 21,
                 "Santolan": 18, "Marikina": 16, "Antipolo": 13}
}

mrt3_fare_matrix = {
    "North Ave": {
        "Quezon Ave": 13, "GMA Kamuning": 13, "Cubao3": 16, 
        "Santolan-Annapolis": 16, "Ortigas": 20, "Shaw Blvd.": 20, 
        "Boni": 20, "Guadalupe": 24, "Buendia": 24, "Ayala": 24, 
        "Magallanes": 28, "Taft Ave": 28
    },
    "Quezon Ave": {
        "North Ave": 13, "GMA Kamuning": 13, "Cubao3": 16, 
        "Santolan-Annapolis": 16, "Ortigas": 16, "Shaw Blvd.": 20, 
        "Boni": 20, "Guadalupe": 20, "Buendia": 24, "Ayala": 24, 
        "Magallanes": 24, "Taft Ave": 28
    },
    "GMA Kamuning": {
        "North Ave": 13, "Quezon Ave": 13, "Cubao3": 13, 
        "Santolan-Annapolis": 13, "Ortigas": 16, "Shaw Blvd.": 16, 
        "Boni": 20, "Guadalupe": 20, "Buendia": 20, "Ayala": 24, 
        "Magallanes": 24, "Taft Ave": 24
    },
    "Cubao3": {
        "North Ave": 16, "Quezon Ave": 16, "GMA Kamuning": 13, 
        "Santolan-Annapolis": 13, "Ortigas": 13, "Shaw Blvd.": 16, 
        "Boni": 16, "Guadalupe": 20, "Buendia": 20, "Ayala": 20, 
        "Magallanes": 24, "Taft Ave": 24
    },
    "Santolan-Annapolis": {
        "North Ave": 16, "Quezon Ave": 16, "GMA Kamuning": 13, 
        "Cubao3": 13, "Ortigas": 13, "Shaw Blvd.": 13, 
        "Boni": 16, "Guadalupe": 16, "Buendia": 20, "Ayala": 20, 
        "Magallanes": 20, "Taft Ave": 24
    },
    "Ortigas": {
        "North Ave": 20, "Quezon Ave": 16, "GMA Kamuning": 16, 
        "Cubao3": 13, "Santolan-Annapolis": 13, "Shaw Blvd.": 13, 
        "Boni": 13, "Guadalupe": 16, "Buendia": 16, "Ayala": 20, 
        "Magallanes": 20, "Taft Ave": 20
    },
    "Shaw Blvd.": {
        "North Ave": 20, "Quezon Ave": 20, "GMA Kamuning": 16, 
        "Cubao3": 16, "Santolan-Annapolis": 13, "Ortigas": 13, 
        "Boni": 13, "Guadalupe": 13, "Buendia": 16, "Ayala": 16, 
        "Magallanes": 20, "Taft Ave": 20
    },
    "Boni": {
        "North Ave": 20, "Quezon Ave": 20, "GMA Kamuning": 20, 
        "Cubao3": 16, "Santolan-Annapolis": 16, "Ortigas": 13, 
        "Shaw Blvd.": 13, "Guadalupe": 13, "Buendia": 16, "Ayala": 16, 
        "Magallanes": 16, "Taft Ave": 20
    },
    "Guadalupe": {
        "North Ave": 24, "Quezon Ave": 20, "GMA Kamuning": 20, 
        "Cubao3": 20, "Santolan-Annapolis": 16, "Ortigas": 16, 
        "Shaw Blvd.": 13, "Boni": 13, "Buendia": 13, "Ayala": 16, 
        "Magallanes": 16, "Taft Ave": 16
    },
    "Buendia": {
        "North Ave": 24, "Quezon Ave": 24, "GMA Kamuning": 20, 
        "Cubao3": 20, "Santolan-Annapolis": 20, "Ortigas": 16, 
        "Shaw Blvd.": 16, "Boni": 16, "Guadalupe": 13, "Ayala": 13, 
        "Magallanes": 16, "Taft Ave": 16
    },
    "Ayala": {
        "North Ave": 24, "Quezon Ave": 24, "GMA Kamuning": 24, 
        "Cubao3": 20, "Santolan-Annapolis": 20, "Ortigas": 20, 
        "Shaw Blvd.": 16, "Boni": 16, "Guadalupe": 13, "Buendia": 13, 
        "Magallanes": 13, "Taft Ave": 13
    },
    "Magallanes": {
        "North Ave": 28, "Quezon Ave": 24, "GMA Kamuning": 24, 
        "Cubao3": 24, "Santolan-Annapolis": 20, "Ortigas": 20, 
        "Shaw Blvd.": 20, "Boni": 16, "Guadalupe": 16, "Buendia": 13, 
        "Ayala": 13, "Taft Ave": 13
    },
    "Taft Ave": {
        "North Ave": 28, "Quezon Ave": 28, "GMA Kamuning": 24, 
        "Cubao3": 24, "Santolan-Annapolis": 24, "Ortigas": 20, 
        "Shaw Blvd.": 20, "Boni": 20, "Guadalupe": 16, "Buendia": 16, 
        "Ayala": 13, "Magallanes": 13
    }
}

# Chat GPT was used to turn the images of the train matrices into python dicts.
