lrt1_fare_matrix = {
    "Baclaran":                 {
        "Baclaran":                 0,
        "EDSA":                     14,
        "Libertad":                 15,
        "Gil Puyat":                16,
        "Vito Cruz":                17,
        "Quirino":                  18,
        "Pedro Gil":                19,
        "United Nations":           20,
        "Central Terminal":         22,
        "Carriedo":                 23,
        "Doroteo Jose":             23,
        "Bambang":                  24,
        "Tayuman":                  25,
        "Blumentritt":              26,
        "Jose Abad Santos":         27,
        "R.Papa":                   28,
        "5th Avenue":               29,
        "Yamaha Monumento":         30,
        "Balintawak":               33,
        "Roosevelt":                35,
    },
    "EDSA":                     {
        "Baclaran":                 14,
        "EDSA":                     0,
        "Libertad":                 15,
        "Gil Puyat":                15,
        "Vito Cruz":                17,
        "Quirino":                  18,
        "Pedro Gil":                19,
        "United Nations":           20,
        "Central Terminal":         21,
        "Carriedo":                 22,
        "Doroteo Jose":             23,
        "Bambang":                  24,
        "Tayuman":                  24,
        "Blumentritt":              25,
        "Jose Abad Santos":         26,
        "R.Papa":                   27,
        "5th Avenue":               28,
        "Yamaha Monumento":         29,
        "Balintawak":               32,
        "Roosevelt":                34,
    },
    "Libertad":                 {
        "Baclaran":                 15,
        "EDSA":                     15,
        "Libertad":                 0,
        "Gil Puyat":                14,
        "Vito Cruz":                15,
        "Quirino":                  16,
        "Pedro Gil":                17,
        "United Nations":           18,
        "Central Terminal":         20,
        "Carriedo":                 21,
        "Doroteo Jose":             22,
        "Bambang":                  22,
        "Tayuman":                  23,
        "Blumentritt":              24,
        "Jose Abad Santos":         25,
        "R.Papa":                   26,
        "5th Avenue":               27,
        "Yamaha Monumento":         28,
        "Balintawak":               31,
        "Roosevelt":                33,
    },
    "Gil Puyat":                {
        "Baclaran":                 16,
        "EDSA":                     15,
        "Libertad":                 14,
        "Gil Puyat":                0,
        "Vito Cruz":                15,
        "Quirino":                  16,
        "Pedro Gil":                17,
        "United Nations":           17,
        "Central Terminal":         19,
        "Carriedo":                 20,
        "Doroteo Jose":             21,
        "Bambang":                  21,
        "Tayuman":                  22,
        "Blumentritt":              23,
        "Jose Abad Santos":         24,
        "R.Papa":                   25,
        "5th Avenue":               26,
        "Yamaha Monumento":         27,
        "Balintawak":               30,
        "Roosevelt":                32,
    },
    "Vito Cruz":                {
        "Baclaran":                 17,
        "EDSA":                     17,
        "Libertad":                 15,
        "Gil Puyat":                15,
        "Vito Cruz":                0,
        "Quirino":                  14,
        "Pedro Gil":                15,
        "United Nations":           16,
        "Central Terminal":         18,
        "Carriedo":                 19,
        "Doroteo Jose":             19,
        "Bambang":                  20,
        "Tayuman":                  21,
        "Blumentritt":              22,
        "Jose Abad Santos":         23,
        "R.Papa":                   24,
        "5th Avenue":               25,
        "Yamaha Monumento":         26,
        "Balintawak":               29,
        "Roosevelt":                31,
    },
    "Quirino":                  {
        "Baclaran":                 18,
        "EDSA":                     18,
        "Libertad":                 16,
        "Gil Puyat":                16,
        "Vito Cruz":                14,
        "Quirino":                  0,
        "Pedro Gil":                14,
        "United Nations":           15,
        "Central Terminal":         17,
        "Carriedo":                 18,
        "Doroteo Jose":             18,
        "Bambang":                  19,
        "Tayuman":                  20,
        "Blumentritt":              21,
        "Jose Abad Santos":         22,
        "R.Papa":                   23,
        "5th Avenue":               24,
        "Yamaha Monumento":         25,
        "Balintawak":               26,
        "Roosevelt":                30,
    },
    "Pedro Gil":                {
        "Baclaran":                 19,
        "EDSA":                     19,
        "Libertad":                 17,
        "Gil Puyat":                17,
        "Vito Cruz":                15,
        "Quirino":                  14,
        "Pedro Gil":                0,
        "United Nations":           14,
        "Central Terminal":         16,
        "Carriedo":                 17,
        "Doroteo Jose":             17,
        "Bambang":                  18,
        "Tayuman":                  19,
        "Blumentritt":              20,
        "Jose Abad Santos":         21,
        "R.Papa":                   22,
        "5th Avenue":               23,
        "Yamaha Monumento":         24,
        "Balintawak":               27,
        "Roosevelt":                29,
    },
    "United Nations":           {
        "Baclaran":                 20,
        "EDSA":                     20,
        "Libertad":                 18,
        "Gil Puyat":                17,
        "Vito Cruz":                16,
        "Quirino":                  15,
        "Pedro Gil":                14,
        "United Nations":           0,
        "Central Terminal":         15,
        "Carriedo":                 16,
        "Doroteo Jose":             16,
        "Bambang":                  17,
        "Tayuman":                  18,
        "Blumentritt":              19,
        "Jose Abad Santos":         20,
        "R.Papa":                   21,
        "5th Avenue":               22,
        "Yamaha Monumento":         23,
        "Balintawak":               26,
        "Roosevelt":                28,
    },
    "Central Terminal":         {
        "Baclaran":                 22,
        "EDSA":                     21,
        "Libertad":                 20,
        "Gil Puyat":                19,
        "Vito Cruz":                18,
        "Quirino":                  17,
        "Pedro Gil":                16,
        "United Nations":           15,
        "Central Terminal":         0,
        "Carriedo":                 14,
        "Doroteo Jose":             15,
        "Bambang":                  16,
        "Tayuman":                  17,
        "Blumentritt":              17,
        "Jose Abad Santos":         18,
        "R.Papa":                   19,
        "5th Avenue":               20,
        "Yamaha Monumento":         22,
        "Balintawak":               24,
        "Roosevelt":                27,
    },
    "Carriedo":                 {
        "Baclaran":                 23,
        "EDSA":                     22,
        "Libertad":                 21,
        "Gil Puyat":                20,
        "Vito Cruz":                19,
        "Quirino":                  18,
        "Pedro Gil":                17,
        "United Nations":           16,
        "Central Terminal":         14,
        "Carriedo":                 0,
        "Doroteo Jose":             14,
        "Bambang":                  15,
        "Tayuman":                  16,
        "Blumentritt":              16,
        "Jose Abad Santos":         18,
        "R.Papa":                   18,
        "5th Avenue":               20,
        "Yamaha Monumento":         21,
        "Balintawak":               24,
        "Roosevelt":                26,
    },
    "Doroteo Jose":             {
        "Baclaran":                 23,
        "EDSA":                     23,
        "Libertad":                 22,
        "Gil Puyat":                21,
        "Vito Cruz":                19,
        "Quirino":                  18,
        "Pedro Gil":                17,
        "United Nations":           16,
        "Central Terminal":         15,
        "Carriedo":                 14,
        "Doroteo Jose":             0,
        "Bambang":                  14,
        "Tayuman":                  15,
        "Blumentritt":              16,
        "Jose Abad Santos":         17,
        "R.Papa":                   18,
        "5th Avenue":               19,
        "Yamaha Monumento":         20,
        "Balintawak":               23,
        "Roosevelt":                25,
    },
    "Bambang":                  {
        "Baclaran":                 24,
        "EDSA":                     24,
        "Libertad":                 22,
        "Gil Puyat":                21,
        "Vito Cruz":                20,
        "Quirino":                  16,
        "Pedro Gil":                18,
        "United Nations":           17,
        "Central Terminal":         16,
        "Carriedo":                 15,
        "Doroteo Jose":             14,
        "Bambang":                  0,
        "Tayuman":                  14,
        "Blumentritt":              15,
        "Jose Abad Santos":         16,
        "R.Papa":                   17,
        "5th Avenue":               18,
        "Yamaha Monumento":         19,
        "Balintawak":               22,
        "Roosevelt":                24,
    },
    "Tayuman":                  {
        "Baclaran":                 25,
        "EDSA":                     24,
        "Libertad":                 23,
        "Gil Puyat":                22,
        "Vito Cruz":                21,
        "Quirino":                  20,
        "Pedro Gil":                19,
        "United Nations":           18,
        "Central Terminal":         17,
        "Carriedo":                 16,
        "Doroteo Jose":             15,
        "Bambang":                  14,
        "Tayuman":                  0,
        "Blumentritt":              14,
        "Jose Abad Santos":         15,
        "R.Papa":                   16,
        "5th Avenue":               17,
        "Yamaha Monumento":         18,
        "Balintawak":               21,
        "Roosevelt":                23,
    },
    "Blumentritt":              {
        "Baclaran":                 26,
        "EDSA":                     25,
        "Libertad":                 24,
        "Gil Puyat":                23,
        "Vito Cruz":                22,
        "Quirino":                  21,
        "Pedro Gil":                20,
        "United Nations":           19,
        "Central Terminal":         17,
        "Carriedo":                 16,
        "Doroteo Jose":             16,
        "Bambang":                  15,
        "Tayuman":                  14,
        "Blumentritt":              0,
        "Jose Abad Santos":         14,
        "R.Papa":                   15,
        "5th Avenue":               16,
        "Yamaha Monumento":         18,
        "Balintawak":               20,
        "Roosevelt":                23,
    },
    "Jose Abad Santos":         {
        "Baclaran":                 27,
        "EDSA":                     26,
        "Libertad":                 25,
        "Gil Puyat":                24,
        "Vito Cruz":                23,
        "Quirino":                  22,
        "Pedro Gil":                21,
        "United Nations":           20,
        "Central Terminal":         18,
        "Carriedo":                 18,
        "Doroteo Jose":             17,
        "Bambang":                  16,
        "Tayuman":                  15,
        "Blumentritt":              14,
        "Jose Abad Santos":         0,
        "R.Papa":                   14,
        "5th Avenue":               15,
        "Yamaha Monumento":         17,
        "Balintawak":               19,
        "Roosevelt":                22,
    },
    "R.Papa":                   {
        "Baclaran":                 28,
        "EDSA":                     27,
        "Libertad":                 26,
        "Gil Puyat":                25,
        "Vito Cruz":                24,
        "Quirino":                  23,
        "Pedro Gil":                22,
        "United Nations":           21,
        "Central Terminal":         19,
        "Carriedo":                 18,
        "Doroteo Jose":             18,
        "Bambang":                  17,
        "Tayuman":                  16,
        "Blumentritt":              15,
        "Jose Abad Santos":         14,
        "R.Papa":                   0,
        "5th Avenue":               14,
        "Yamaha Monumento":         16,
        "Balintawak":               18,
        "Roosevelt":                21,
    },
    "5th Avenue":               {
        "Baclaran":                 29,
        "EDSA":                     28,
        "Libertad":                 27,
        "Gil Puyat":                26,
        "Vito Cruz":                25,
        "Quirino":                  24,
        "Pedro Gil":                23,
        "United Nations":           22,
        "Central Terminal":         20,
        "Carriedo":                 20,
        "Doroteo Jose":             19,
        "Bambang":                  18,
        "Tayuman":                  17,
        "Blumentritt":              16,
        "Jose Abad Santos":         15,
        "R.Papa":                   14,
        "5th Avenue":               0,
        "Yamaha Monumento":         15,
        "Balintawak":               17,
        "Roosevelt":                20,
    },
    "Yamaha Monumento":         {
        "Baclaran":                 30,
        "EDSA":                     29,
        "Libertad":                 28,
        "Gil Puyat":                27,
        "Vito Cruz":                26,
        "Quirino":                  25,
        "Pedro Gil":                24,
        "United Nations":           23,
        "Central Terminal":         22,
        "Carriedo":                 21,
        "Doroteo Jose":             20,
        "Bambang":                  19,
        "Tayuman":                  18,
        "Blumentritt":              18,
        "Jose Abad Santos":         17,
        "R.Papa":                   16,
        "5th Avenue":               15,
        "Yamaha Monumento":         0,
        "Balintawak":               16,
        "Roosevelt":                18,
    },
    "Balintawak":               {
        "Baclaran":                 33,
        "EDSA":                     32,
        "Libertad":                 31,
        "Gil Puyat":                30,
        "Vito Cruz":                29,
        "Quirino":                  28,
        "Pedro Gil":                27,
        "United Nations":           26,
        "Central Terminal":         24,
        "Carriedo":                 24,
        "Doroteo Jose":             23,
        "Bambang":                  22,
        "Tayuman":                  21,
        "Blumentritt":              20,
        "Jose Abad Santos":         19,
        "R.Papa":                   18,
        "5th Avenue":               17,
        "Yamaha Monumento":         16,
        "Balintawak":               0,
        "Roosevelt":                16,
    },
    "Roosevelt":                {
        "Baclaran":                 35,
        "EDSA":                     34,
        "Libertad":                 33,
        "Gil Puyat":                32,
        "Vito Cruz":                31,
        "Quirino":                  30,
        "Pedro Gil":                29,
        "United Nations":           28,
        "Central Terminal":         27,
        "Carriedo":                 26,
        "Doroteo Jose":             25,
        "Bambang":                  24,
        "Tayuman":                  23,
        "Blumentritt":              23,
        "Jose Abad Santos":         22,
        "R.Papa":                   21,
        "5th Avenue":               20,
        "Yamaha Monumento":         18,
        "Balintawak":               16,
        "Roosevelt":                0,
    },
}

lrt2_fare_matrix = {
    "Recto": {"Recto": 13, "Legarda": 15, "Pureza": 16, "V. Mapa": 18, "J. Ruiz": 19,
              "Gilmore": 21, "Betty Go": 22, "Cubao2": 23, "Anonas": 25, "Katipunan": 26,
              "Santolan": 28, "Marikina": 31, "Antipolo": 33},
    
    "Legarda": {"Recto": 15, "Legarda": 13, "Pureza": 15, "V. Mapa": 17, "J. Ruiz": 18,
                "Gilmore": 19, "Betty Go": 21, "Cubao2": 22, "Anonas": 24, "Katipunan": 25,
                "Santolan": 27, "Marikina": 29, "Antipolo": 32},
    
    "Pureza": {"Recto": 16, "Legarda": 15, "Pureza": 13, "V. Mapa": 15, "J. Ruiz": 16,
               "Gilmore": 18, "Betty Go": 19, "Cubao2": 20, "Anonas": 22, "Katipunan": 23,
               "Santolan": 26, "Marikina": 28, "Antipolo": 30},
    
    "V. Mapa": {"Recto": 18, "Legarda": 17, "Pureza": 15, "V. Mapa": 13, "J. Ruiz": 15,
                "Gilmore": 17, "Betty Go": 19, "Cubao2": 20, "Anonas": 22, "Katipunan": 24,
                "Santolan": 26, "Marikina": 29, "Antipolo": 30},
    
    "J. Ruiz": {"Recto": 19, "Legarda": 18, "Pureza": 16, "V. Mapa": 15, "J. Ruiz": 13,
                "Gilmore": 16, "Betty Go": 17, "Cubao2": 19, "Anonas": 20, "Katipunan": 22,
                "Santolan": 24, "Marikina": 27, "Antipolo": 29},
    
    "Gilmore": {"Recto": 21, "Legarda": 19, "Pureza": 18, "V. Mapa": 16, "J. Ruiz": 14,
                "Gilmore": 13, "Betty Go": 15, "Cubao2": 16, "Anonas": 18, "Katipunan": 19,
                "Santolan": 21, "Marikina": 23, "Antipolo": 26},
    
    "Betty Go": {"Recto": 22, "Legarda": 21, "Pureza": 19, "V. Mapa": 17, "J. Ruiz": 16,
                 "Gilmore": 13, "Betty Go": 13, "Cubao2": 15, "Anonas": 16, "Katipunan": 18,
                 "Santolan": 20, "Marikina": 22, "Antipolo": 25},
    
    "Cubao2": {"Recto": 23, "Legarda": 22, "Pureza": 20, "V. Mapa": 17, "J. Ruiz": 16,
              "Gilmore": 15, "Betty Go": 13, "Cubao2": 13, "Anonas": 15, "Katipunan": 16,
              "Santolan": 19, "Marikina": 21, "Antipolo": 23},
    
    "Anonas": {"Recto": 25, "Legarda": 24, "Pureza": 22, "V. Mapa": 19, "J. Ruiz": 18,
               "Gilmore": 16, "Betty Go": 15, "Cubao2": 13, "Anonas": 13, "Katipunan": 14,
               "Santolan": 17, "Marikina": 19, "Antipolo": 22},
    
    "Katipunan": {"Recto": 26, "Legarda": 25, "Pureza": 23, "V. Mapa": 20, "J. Ruiz": 19,
                  "Gilmore": 18, "Betty Go": 16, "Cubao2": 15, "Anonas": 13, "Katipunan": 13,
                  "Santolan": 16, "Marikina": 18, "Antipolo": 21},
    
    "Santolan": {"Recto": 28, "Legarda": 27, "Pureza": 26, "V. Mapa": 22, "J. Ruiz": 21,
                 "Gilmore": 19, "Betty Go": 18, "Cubao2": 16, "Anonas": 14, "Katipunan": 13,
                 "Santolan": 13, "Marikina": 15, "Antipolo": 18},
    
    "Marikina": {"Recto": 31, "Legarda": 29, "Pureza": 28, "V. Mapa": 26, "J. Ruiz": 24,
                 "Gilmore": 23, "Betty Go": 22, "Cubao2": 21, "Anonas": 19, "Katipunan": 18,
                 "Santolan": 15, "Marikina": 13, "Antipolo": 16},
    
    "Antipolo": {"Recto": 33, "Legarda": 32, "Pureza": 30, "V. Mapa": 29, "J. Ruiz": 27,
                 "Gilmore": 26, "Betty Go": 25, "Cubao2": 23, "Anonas": 22, "Katipunan": 21,
                 "Santolan": 18, "Marikina": 16, "Antipolo": 13}
}

mrt3_fare_matrix = {
    "North Ave": {
        "Quezon Ave": 13, "GMA Kamuning": 13, "Cubao3": 16, 
        "Santolan-Annapolis": 16, "Ortigas": 20, "Shaw Blvd.": 20, 
        "Boni": 20, "Guadalupe": 24, "Buendia": 24, "Ayala": 24, 
        "Magallanes": 28, "Taft Ave": 28
    },
    "Quezon Ave": {
        "North Ave": 13, "GMA Kamuning": 13, "Cubao3": 16, 
        "Santolan-Annapolis": 16, "Ortigas": 16, "Shaw Blvd.": 20, 
        "Boni": 20, "Guadalupe": 20, "Buendia": 24, "Ayala": 24, 
        "Magallanes": 24, "Taft Ave": 28
    },
    "GMA Kamuning": {
        "North Ave": 13, "Quezon Ave": 13, "Cubao3": 13, 
        "Santolan-Annapolis": 13, "Ortigas": 16, "Shaw Blvd.": 16, 
        "Boni": 20, "Guadalupe": 20, "Buendia": 20, "Ayala": 24, 
        "Magallanes": 24, "Taft Ave": 24
    },
    "Cubao3": {
        "North Ave": 16, "Quezon Ave": 16, "GMA Kamuning": 13, 
        "Santolan-Annapolis": 13, "Ortigas": 13, "Shaw Blvd.": 16, 
        "Boni": 16, "Guadalupe": 20, "Buendia": 20, "Ayala": 20, 
        "Magallanes": 24, "Taft Ave": 24
    },
    "Santolan-Annapolis": {
        "North Ave": 16, "Quezon Ave": 16, "GMA Kamuning": 13, 
        "Cubao3": 13, "Ortigas": 13, "Shaw Blvd.": 13, 
        "Boni": 16, "Guadalupe": 16, "Buendia": 20, "Ayala": 20, 
        "Magallanes": 20, "Taft Ave": 24
    },
    "Ortigas": {
        "North Ave": 20, "Quezon Ave": 16, "GMA Kamuning": 16, 
        "Cubao3": 13, "Santolan-Annapolis": 13, "Shaw Blvd.": 13, 
        "Boni": 13, "Guadalupe": 16, "Buendia": 16, "Ayala": 20, 
        "Magallanes": 20, "Taft Ave": 20
    },
    "Shaw Blvd.": {
        "North Ave": 20, "Quezon Ave": 20, "GMA Kamuning": 16, 
        "Cubao3": 16, "Santolan-Annapolis": 13, "Ortigas": 13, 
        "Boni": 13, "Guadalupe": 13, "Buendia": 16, "Ayala": 16, 
        "Magallanes": 20, "Taft Ave": 20
    },
    "Boni": {
        "North Ave": 20, "Quezon Ave": 20, "GMA Kamuning": 20, 
        "Cubao3": 16, "Santolan-Annapolis": 16, "Ortigas": 13, 
        "Shaw Blvd.": 13, "Guadalupe": 13, "Buendia": 16, "Ayala": 16, 
        "Magallanes": 16, "Taft Ave": 20
    },
    "Guadalupe": {
        "North Ave": 24, "Quezon Ave": 20, "GMA Kamuning": 20, 
        "Cubao3": 20, "Santolan-Annapolis": 16, "Ortigas": 16, 
        "Shaw Blvd.": 13, "Boni": 13, "Buendia": 13, "Ayala": 16, 
        "Magallanes": 16, "Taft Ave": 16
    },
    "Buendia": {
        "North Ave": 24, "Quezon Ave": 24, "GMA Kamuning": 20, 
        "Cubao3": 20, "Santolan-Annapolis": 20, "Ortigas": 16, 
        "Shaw Blvd.": 16, "Boni": 16, "Guadalupe": 13, "Ayala": 13, 
        "Magallanes": 16, "Taft Ave": 16
    },
    "Ayala": {
        "North Ave": 24, "Quezon Ave": 24, "GMA Kamuning": 24, 
        "Cubao3": 20, "Santolan-Annapolis": 20, "Ortigas": 20, 
        "Shaw Blvd.": 16, "Boni": 16, "Guadalupe": 13, "Buendia": 13, 
        "Magallanes": 13, "Taft Ave": 13
    },
    "Magallanes": {
        "North Ave": 28, "Quezon Ave": 24, "GMA Kamuning": 24, 
        "Cubao3": 24, "Santolan-Annapolis": 20, "Ortigas": 20, 
        "Shaw Blvd.": 20, "Boni": 16, "Guadalupe": 16, "Buendia": 13, 
        "Ayala": 13, "Taft Ave": 13
    },
    "Taft Ave": {
        "North Ave": 28, "Quezon Ave": 28, "GMA Kamuning": 24, 
        "Cubao3": 24, "Santolan-Annapolis": 24, "Ortigas": 20, 
        "Shaw Blvd.": 20, "Boni": 20, "Guadalupe": 16, "Buendia": 16, 
        "Ayala": 13, "Magallanes": 13
    }
}

# Chat GPT was used to turn the images of the train matrices into python dicts.
