# Generated by Django 5.1.5 on 2025-02-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainLine', models.CharField(max_length=255)),
                ('ocation', models.CharField(max_length=255)),
                ('currentStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='station',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='station',
            name='name',
        ),
        migrations.AddField(
            model_name='station',
            name='cctv',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='isOperating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='leftCurrentDensity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='leftETA',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='leftHistory',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='rightCurrentDensity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='rightETA',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='rightHistory',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='stationIMG',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='stationName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='trainLine',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
