# Generated by Django 5.1.6 on 2025-03-13 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_remove_station_cctv_remove_station_lefthistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydensity',
            name='leftDensity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydensity',
            name='rightDensity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydensity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='hourlydensity',
            name='leftDensity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlydensity',
            name='rightDensity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlydensity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
