# Generated by Django 5.1.6 on 2025-03-19 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0003_alter_dailydensity_leftdensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='leftETA',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='rightETA',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
