# Generated by Django 5.1.6 on 2025-03-25 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0004_alter_station_lefteta_alter_station_righteta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='leftETA',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='rightETA',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
