# Generated by Django 5.1.6 on 2025-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0005_alter_station_lefteta_alter_station_righteta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='stationIMG',
        ),
        migrations.AddField(
            model_name='station',
            name='stationImage',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
