STATION_ID_TO_NAME = {
    1: "Roosevelt",
    2: "Balintawak",
    3: "Monumento",
    4: "5th Avenue",
    5: "R. Papa",
    6: "Abad Santos",
    7: "Blumentritt",
    8: "Tayuman",
    9: "Bambang",
    10: "Doroteo Jose",
    11: "Carriedo",
    12: "Central Terminal",
    13: "United Nations",
    14: "Pedro Gil",
    15: "Quirino",
    16: "Vito Cruz",
    17: "Gil Puyat",
    18: "Libertad",
    19: "EDSA",
    20: "Baclaran",
    21: "Recto",
    22: "Legarda",
    23: "Pureza",
    24: "V. Mapa",
    25: "J. Ruiz",
    26: "Gilmore",
    27: "Betty Go-Belmonte",
    28: "Araneta-Cubao",
    29: "Anonas",
    30: "Katipunan",
    31: "Santolan2",
    32: "Marikina",
    33: "Antipolo",
    34: "North Avenue",
    35: "Quezon Avenue",
    36: "Kamuning",
    37: "Cubao",
    38: "Santolan3",
    39: "Ortigas",
    40: "Shaw Blvd.",
    41: "Boni",
    42: "Guadalupe",
    43: "Buendia",
    44: "Ayala",
    45: "Magallanes",
    46: "Taft"
}

STATION_NAME_TO_ID = {
    "Roosevelt": 1,
    "Balintawak": 2,
    "Monumento": 3,
    "5th Avenue": 4,
    "R. Papa": 5,
    "Abad Santos": 6,
    "Blumentritt": 7,
    "Tayuman": 8,
    "Bambang": 9,
    "Doroteo Jose": 10,
    "Carriedo": 11,
    "Central Terminal": 12,
    "United Nations": 13,
    "Pedro Gil": 14,
    "Quirino": 15,
    "Vito Cruz": 16,
    "Gil Puyat": 17,
    "Libertad": 18,
    "EDSA": 19,
    "Baclaran": 20,
    "Recto": 21,
    "Legarda": 22,
    "Pureza": 23,
    "V. Mapa": 24,
    "J. Ruiz": 25,
    "Gilmore": 26,
    "Betty Go-Belmonte": 27,
    "Araneta-Cubao": 28,
    "Anonas": 29,
    "Katipunan": 30,
    "Santolan2": 31,
    "Marikina": 32,
    "Antipolo": 33,
    "North Avenue": 34,
    "Quezon Avenue": 35,
    "Kamuning": 36,
    "Cubao": 37,
    "Santolan3": 38,
    "Ortigas": 39,
    "Shaw Blvd.": 40,
    "Boni": 41,
    "Guadalupe": 42,
    "Buendia": 43,
    "Ayala": 44,
    "Magallanes": 45,
    "Taft": 46
}
