# Generated by Django 5.1.6 on 2025-03-13 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='datetimePosted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
