# Generated by Django 5.1.6 on 2025-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superAdmin', 'Super Admin')], default='admin', max_length=20),
        ),
    ]
