# Generated by Django 5.1.6 on 2025-02-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_adminuser_name_alter_adminuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
